#!/bin/sh

# Change this to choose wanted languages
WANTED_LANGS=(
    "und"
    "eng"
    "swe"
    "jap"
    "jpn"
)

# Paths to used programs
MKVMERGE=$(which mkvmerge)
FIND=$(which find)

cleanFile() {
    if ! test -f "$1"; then
        echo 'FILE is not a regular file' >&2
        exit 2
    fi

    FILE=$1

    # Run mkvmerge identify to check contents of file
    OUTPUT=$($MKVMERGE --identify-verbose "$FILE")

    # If failure, skip out and continue loop
    if test $? -ne 0; then
        echo 'Failed to identify '$FILE >&2
        continue
    fi
}

cleanDirectory() {
    $FIND $1 -type f -iname '*.mkv' -print0 | while read -d $'\0' FILE; do
        cleanFile "$FILE"
    done
}

# If parameter is a file, run this file
if test -f "$1"; then
    cleanFile "$1"
fi

# If parameter is a directory, run for directories
if test -d "$1"; then
    cleanDirectory "$1"
fi
